### ISSUE TITLE
System "cl-edn" not found

### ISSUE THREAD

**Issue by lilactown** [fiddlerwoaroof/cl-edn#1]
I've cloned the repo into my `~/quicklisp/local-projects/` dir and started a slime REPL, however when I run quickload it isn't able to find the system:

```lisp
* (ql:quickload :cl-edn)

debugger invoked on a QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread
#<THREAD "main thread" RUNNING {10005505B3}>:
  System "cl-edn" not found
```

**Comment by fiddlerwoaroof** [comment]
Can you do `ls -ld ~/quicklisp/local-projects/*` and ``ls -l ~/quicklisp/local-projects/cl-edn`?

**Comment by lilactown** [comment]
```
$ ls -ld ~/quicklisp/local-projects/*
drwxr-xr-x  15 r627543  RBSWA\Domain Users  480 Jul 24 11:38 /Users/r627543/quicklisp/local-projects/cl-edn
-rw-r--r--   1 r627543  RBSWA\Domain Users    0 Jul 13 10:02 /Users/r627543/quicklisp/local-projects/system-index.txt
```

```
ls -l ~/quicklisp/local-projects/cl-edn
total 112
-rw-r--r--  1 r627543  RBSWA\Domain Users   1071 Jul 24 11:38 LICENSE
-rw-r--r--  1 r627543  RBSWA\Domain Users   3562 Jul 24 11:38 README.html
-rw-r--r--  1 r627543  RBSWA\Domain Users   2878 Jul 24 11:38 README.md
-rw-r--r--  1 r627543  RBSWA\Domain Users   1193 Jul 24 11:38 cl-edn.asd
-rw-r--r--  1 r627543  RBSWA\Domain Users  10177 Jul 24 11:38 edn.lisp
-rw-r--r--  1 r627543  RBSWA\Domain Users   1274 Jul 24 11:38 fset-lossy-synthesize.lisp
-rw-r--r--  1 r627543  RBSWA\Domain Users   1150 Jul 24 11:38 fset-synthesize.lisp
-rw-r--r--  1 r627543  RBSWA\Domain Users   4838 Jul 24 11:38 generate-edn.lisp
-rw-r--r--  1 r627543  RBSWA\Domain Users    550 Jul 24 11:38 package.lisp
-rw-r--r--  1 r627543  RBSWA\Domain Users   2621 Jul 24 11:38 synthesize.lisp
-rw-r--r--  1 r627543  RBSWA\Domain Users   1669 Jul 24 11:38 test.lisp
```

**Comment by fiddlerwoaroof** [comment]
In your slime repl, try running `(ql:register-local-projects)` before loading :cl-edn

**Comment by fiddlerwoaroof** [comment]
Also, I just pushed some changes that fix a (probably unrelated) issue.  It turns out that you'll also need to clone https://github.com/fiddlerwoaroof/fwoar.lisputils.git into local-projects before anything works.

**Comment by fiddlerwoaroof** [comment]
Hmm, I just noticed that the group in the second directory listing windows group. Are you running in WSL or on Windows otherwise?

**Comment by lilactown** [comment]
Nope, I'm on macOS.

After futzing around with it some more, I figured out the issue: I had previously installed SBCL + quicklisp on their own, and then switched to using roswell. roswell installs quicklisp and configures it's local projects to live under `~/.roswell/local-projects/`.

Sorry for the issue! I'm very new to the Lisp ecosystem.

I'm getting a compile error now but I'll open a separate issue for that.
