### ISSUE TITLE
Compile error on quickload

### ISSUE THREAD

**Issue by lilactown** [fiddlerwoaroof/cl-edn#2]
I have cloned this system and https://github.com/fiddlerwoaroof/fwoar.lisputils into my local projects.

```
CL-USER> (ql:list-local-systems)
("cl-edn" "fwoar.lisputils")
```
However, when I run `(ql:quickload :cl-edn)` I get the follow compile error message:

```
; SLIME 2.21
CL-USER> (ql:quickload :cl-edn)
To load "cl-edn":
  Load 1 ASDF system:
    cl-edn
; Loading "cl-edn"
.To load "asdf-package-system":
  Load 1 ASDF system:
    asdf-package-system
; Loading "asdf-package-system"

...
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Package FW.LU does not exist.
;   
;       Line: 51, Column: 27, File-Position: 2065
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /Users/will/.roswell/local-projects/cl-edn/synthesize.lisp" {1002C831A3}>
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 1 ERROR condition
```

**Comment by fiddlerwoaroof** [comment]
Which commit have you cloned?

**Comment by fiddlerwoaroof** [comment]
Sorry, it should work now. I didn’t actually push the commits I thought I had.

**Comment by lilactown** [comment]
Great! Pulling master has it compiling. I appreciate you helping me with this.

I've now loaded cl-edn into my REPL, and tried:
```
* (edn:parse "foo")

debugger invoked on a SB-PCL:CLASS-NOT-FOUND-ERROR in thread
#<THREAD "main thread" RUNNING {10005505B3}>:
  There is no class named EDN:FSET.
```

Am I reading the README right?

**Comment by fiddlerwoaroof** [comment]
The README is probably outdated on this point.  The system is divided into two parts: the reader and a bunch of synthesizers that convert EDN into lisp objects. `(edn:parse "foo")` combines these two roles, `(edn:read-edn "foo")` only reads the EDN into an AST.  You'll have to also load a synthesizer implementation by doing something like `(ql:quickload :cl-edn/fset)`.

Sorry about all the issues, I'm so used to the library that I'm bad at documenting it.

**Comment by lilactown** [comment]
🙌 that worked! If it helps, I'll open up a PR with some additional instructions in the README.

I appreciate the help, and the library - I started learning Lisp to make some CLI apps leveraging EDN, and started to naively implement my own parser using the readtable, when I saw your library and figured I'd save myself the pain of that endeavor!

**Comment by fiddlerwoaroof** [comment]
My parser works, I've been currently optimizing it for large inputs: right now, on sbcl, it takes about 6 seconds to process a 6.2MB EDN file that Clojure parses in a second or two.  I think this might be because I'm using parser-combinators but, unless you're handling a lot of big files, it should be fast enough.

**Comment by fiddlerwoaroof** [comment]
I've pushed some README changes, it'd be great to get a PR with some documentation changes from a new-user's perspective.  Also, if you open-source anything, let me know if you want me to link it as an example use.
